### ISSUE TITLE
App crashed when opened (sometimes)

### ISSUE THREAD

**Issue by Mojienjoynent** [Chooloo/koler#212]
## Checklist

App crashed when opened , but now work well. This is a log... Sorry . I can't upload anywehere

### Logs

Log:

FATAL EXCEPTION: main
Process: com.chooloo.www.koler, PID: 2513
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chooloo.www.koler/com.chooloo.www.koler.ui.main.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.chooloo.www.koler.ui.base.BottomFragment: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.chooloo.www.koler.ui.base.BottomFragment: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2466)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at com.chooloo.www.koler.ui.base.BaseActivity.onCreate(BaseActivity.kt:13)
	at com.chooloo.www.koler.ui.main.MainActivity.onCreate(MainActivity.kt:50)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	... 10 more
Caused by: java.lang.NoSuchMethodException: <init> []
	at java.lang.Class.getConstructor0(Class.java:2204)
	at java.lang.Class.getConstructor(Class.java:1683)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
	... 22 more

### Device info
 - Android version/Custom ROM version: Los 14.1
 - Device model: Huawei -y360

**Comment by roeiedri** [comment]
Is this from the latest release?

**Comment by ueen** [comment]
Latest release, crash on contact selected (latest android 11 on pixel)

**Comment by reddtse** [comment]
App keeps crashing everytime I click on an contact name. Android 10 user here.

**Comment by ueen** [comment]
Did you you update to the latest release from today? Having no issues on Android 11

**Comment by reddtse** [comment]
Hi! Yeah, app seems working now! Also, would you like to publish your work on skydroid? The page said it's an open source and decentralized android app store. Wouldn't hurt to try it, would it?

Another thing, I hope you're open to checking out UI suggestions because I'll be bothering you in the future lol. I'm a Samsung user and sadly, my unit didn't get the recent One UI updates so my apps will remain bland and lame now.

PS: Wanna ask if you can add a call recorder feature to Koler? Would love that. Asked Samsung CSR about it and they said it violates their privacy policy, not sure what that means since they're collecting their users' data anyway but...mkay. Just sharing some thoughts. Really cool app you have there, really. And oh, can you also please add some animations or cute things like that when you're in a call? 🙂😁

Cheers!

Red

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DigitalNXZ** [comment]
https://github.com/Chooloo/koler/projects/1#card-44417179 @reddtse it's already on the list since 2020 :)

**Comment by roeiedri** [comment]
Yeah thats also a point but ive actually started to work on a recorder some time ago and it got delayed.
Its a bit of a pain in the ass coding wise bit i hope ill finish it eventually.
Btw @DigitalNXZ dont notice the todo page on github, didnt touch that in more than a year.

**Comment by reddtse** [comment]
Yeah I saw that circular icon on the app when I was making a call. Turns out that the call wasn't recorded.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
