### ISSUE TITLE
Crash on Device Orientation

### ISSUE THREAD

**Issue by shuvashish76** [Chooloo/koler#245]
- [x] I am using the latest version - 1.0.9 (F-droid version)
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
App crashed while.
1. Turn on device rotation & change orientation to one side
2. Click on Manage Blocked numbers
3. Click on the back icon

Ok, device orientation is not supported yet #244 but it should not crash at least.
(I'm not a dev. I guess it is related to #212)

### Logs
FATAL EXCEPTION: main
Process: com.chooloo.www.koler, PID: 9442
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chooloo.www.koler/com.chooloo.www.koler.ui.main.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.chooloo.www.koler.ui.base.BottomFragment: could not find Fragment constructor
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
 at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4702)
 at android.app.ActivityThread.-wrap18(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6518)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.chooloo.www.koler.ui.base.BottomFragment: could not find Fragment constructor
 at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
 at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
 at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
 at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
 at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2466)
 at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
 at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
 at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
 at com.chooloo.www.koler.ui.base.BaseActivity.onCreate(BaseActivity.kt:13)
 at com.chooloo.www.koler.ui.main.MainActivity.onCreate(MainActivity.kt:51)
 at android.app.Activity.performCreate(Activity.java:7023)
 at android.app.Activity.performCreate(Activity.java:7014)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
 ... 10 more
Caused by: java.lang.NoSuchMethodException: <init> []
 at java.lang.Class.getConstructor0(Class.java:2320)
 at java.lang.Class.getConstructor(Class.java:1725)
 at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
 ... 23 more

### Device info
 - Android version: 8.1.0
 - Device model: Lenovo Tab4 8 Plus (TB-8704X)

**Comment by shuvashish76** [comment]
**Steps to reproduce the bug**

Little bit different steps
1.Turn on device rotation & change orientation to one side
2.Click on Manage Blocked numbers
3.While on "Blocked numbers" screen change orientation back to normal
4.Click on the back icon
App crashed

---

**Logs**

FATAL EXCEPTION: main
Process: com.chooloo.www.koler, PID: 25583
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chooloo.www.koler/com.chooloo.www.koler.ui.main.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.chooloo.www.koler.ui.base.BottomFragment: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4702)
	at android.app.ActivityThread.-wrap18(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.chooloo.www.koler.ui.base.BottomFragment: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2466)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at com.chooloo.www.koler.ui.base.BaseActivity.onCreate(BaseActivity.kt:13)
	at com.chooloo.www.koler.ui.main.MainActivity.onCreate(MainActivity.kt:39)
	at android.app.Activity.performCreate(Activity.java:7023)
	at android.app.Activity.performCreate(Activity.java:7014)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
	... 10 more
Caused by: java.lang.NoSuchMethodException: <init> []
	at java.lang.Class.getConstructor0(Class.java:2320)
	at java.lang.Class.getConstructor(Class.java:1725)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
	... 23 more

Checked with **Version v1.1.0 (60)**
