### ISSUE TITLE
Crash while click on Koler from device intent options

### ISSUE THREAD

**Issue by shuvashish76** [Chooloo/koler#252]
## Checklist
- [x] I am using the latest version - 1.0.9 (F-droid version)
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Click/drag (according to your device) phone shortcut from lockscreen
2. It openup option to choose your preferred phone app
![Screenshot_2021-09-03-16-33-49](https://user-images.githubusercontent.com/48226312/131996285-776ded0c-cd29-457a-93f6-f000f9504bb6.jpeg) 
3. Select Koler
App crashes

### Expected behavior
This should open the caller app as it normally does.

### Logs

FATAL EXCEPTION: main
Process: com.chooloo.www.koler, PID: 23907
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chooloo.www.koler/com.chooloo.www.koler.ui.main.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.net.URLDecoder.decode(URLDecoder.java:137)
	at com.chooloo.www.koler.ui.main.MainPresenter.onViewIntent(MainPresenter.kt:19)
	at com.chooloo.www.koler.ui.main.MainActivity.checkIntent(MainActivity.kt:97)
	at com.chooloo.www.koler.ui.main.MainActivity.onSetup(MainActivity.kt:79)
	at com.chooloo.www.koler.ui.base.BaseActivity.onStart(BaseActivity.kt:18)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
	at android.app.Activity.performStart(Activity.java:7043)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2744)
	... 9 more

### Device info
- Android version: 8.1.0
- Device model: Lenovo Tab4 8 Plus (TB-8704X)

I don't think its device specific because it crashed on both my tab & phone.

**Comment by roeiedri** [comment]
What phone shortcut?

**Comment by shuvashish76** [comment]
Lock screen shortcut.

![Screenshot_2021-09-04-18-20-47](https://user-images.githubusercontent.com/48226312/132095012-a7475230-912c-4dbe-935a-014259b40e81.jpeg)

https://user-images.githubusercontent.com/48226312/132095121-488d75ee-7823-4e51-ab84-f6ba67aa7bee.mp4
