### ISSUE TITLE
Close app when I click on "call" button (when default dial is koler) 

### ISSUE THREAD

**Issue by Mojienjoynent** [Chooloo/koler#255]
## Checklist

- [x] I am using the latest version - 1.0.9 latest 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

Show Me the call screen 

(this bug just happen in income NG calls. But all things OK in out
### Expected behavior

Show me the call screen and connect with my contacts...  But I can't... 

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/68327458/132097467-613a2e1f-b26f-4f38-bfdd-1cc941dbb351.mp4

### Logs

java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String[]
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl$askForSim$1$1.invoke(SimInteractorImpl.kt:77)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl$askForSim$1$1.invoke(SimInteractorImpl.kt:16)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl$getSimAccounts$1.invoke(SimInteractorImpl.kt:53)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl$getSimAccounts$1.invoke(SimInteractorImpl.kt:16)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl$getPhoneAccounts$1.invoke(SimInteractorImpl.kt:66)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl$getPhoneAccounts$1.invoke(SimInteractorImpl.kt:16)
	at com.chooloo.www.koler.interactor.permission.PermissionInteractorImpl.checkPermissions(PermissionInteractorImpl.kt:70)
	at com.chooloo.www.koler.interactor.permission.PermissionInteractorImpl.runWithPermissions(PermissionInteractorImpl.kt:92)
	at com.chooloo.www.koler.interactor.permission.PermissionInteractor$DefaultImpls.runWithPermissions$default(PermissionInteractor.kt:30)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl.getPhoneAccounts(SimInteractorImpl.kt:61)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl.getSimAccounts(SimInteractorImpl.kt:52)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl$askForSim$1.invoke(SimInteractorImpl.kt:25)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl$askForSim$1.invoke(SimInteractorImpl.kt:16)
	at com.chooloo.www.koler.interactor.permission.PermissionInteractorImpl.checkPermissions(PermissionInteractorImpl.kt:70)
	at com.chooloo.www.koler.interactor.permission.PermissionInteractorImpl.runWithPermissions(PermissionInteractorImpl.kt:92)
	at com.chooloo.www.koler.interactor.permission.PermissionInteractor$DefaultImpls.runWithPermissions$default(PermissionInteractor.kt:30)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl.askForSim(SimInteractorImpl.kt:24)
	at com.chooloo.www.koler.interactor.navigation.NavigationInteractorImpl$call$1$1.invoke(NavigationInteractorImpl.kt:93)
	at com.chooloo.www.koler.interactor.navigation.NavigationInteractorImpl$call$1$1.invoke(NavigationInteractorImpl.kt:20)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl$getIsMultiSim$1.invoke(SimInteractorImpl.kt:45)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl$getIsMultiSim$1.invoke(SimInteractorImpl.kt:16)
	at com.chooloo.www.koler.interactor.permission.PermissionInteractorImpl.checkPermissions(PermissionInteractorImpl.kt:70)
	at com.chooloo.www.koler.interactor.permission.PermissionInteractorImpl.runWithPermissions(PermissionInteractorImpl.kt:92)
	at com.chooloo.www.koler.interactor.permission.PermissionInteractor$DefaultImpls.runWithPermissions$default(PermissionInteractor.kt:30)
	at com.chooloo.www.koler.interactor.sim.SimInteractorImpl.getIsMultiSim(SimInteractorImpl.kt:44)
	at com.chooloo.www.koler.interactor.navigation.NavigationInteractorImpl$call$1.invoke(NavigationInteractorImpl.kt:91)
	at com.chooloo.www.koler.interactor.navigation.NavigationInteractorImpl$call$1.invoke(NavigationInteractorImpl.kt:20)
	at com.chooloo.www.koler.interactor.permission.PermissionInteractorImpl.runWithDefaultDialer(PermissionInteractorImpl.kt:117)
	at com.chooloo.www.koler.interactor.navigation.NavigationInteractorImpl.call(NavigationInteractorImpl.kt:90)
	at com.chooloo.www.koler.ui.recent.RecentPresenter.onActionCall(RecentPresenter.kt:55)
	at com.chooloo.www.koler.ui.recent.RecentFragment$onSetup$$inlined$apply$lambda$3.onClick(RecentFragment.kt:67)
	at android.view.View.performClick(View.java:7509)
	at android.view.View.performClickInternal(View.java:7486)
	at android.view.View.access$3600(View.java:841)
	at android.view.View$PerformClick.run(View.java:28710)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

### Device info
 - Android version/Custom ROM version: stock miui 12.5 android 11
 - Device model: poco x3 pro

**Comment by roeiedri** [comment]
You have 2 sim cards?

**Comment by Mojienjoynent** [comment]
> You have 2 sim cards?

Yes...

**Comment by roeiedri** [comment]
Added a fix, though I don't have more than 1 sim so I can't test it.
Please test it and update me if the problem still occurs :)

**Comment by Mojienjoynent** [comment]
> Added a fix, though I don't have more than 1 sim so I can't test it.
> Please test it and update me if the problem still occurs :)

OK. Sure
