### ISSUE TITLE
Crash on pasting links/unsupported text on search & koler keyboard

### ISSUE THREAD

**Issue by shuvashish76** [Chooloo/koler#263]
FATAL EXCEPTION: main
Process: com.chooloo.www.koler, PID: 1905
java.lang.IllegalArgumentException: URI: content://com.android.contacts/contacts/filter/./76, calling user: com.chooloo.www.koler, calling package:com.chooloo.www.koler
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
	at android.content.ContentResolver.query(ContentResolver.java:756)
	at android.content.ContentResolver.query(ContentResolver.java:705)
	at android.content.ContentResolver.query(ContentResolver.java:663)
	at com.chooloo.www.koler.contentresolver.BaseContentResolver.queryContent(BaseContentResolver.kt:34)
	at com.chooloo.www.koler.contentresolver.BaseContentResolver.getContent(BaseContentResolver.kt:16)
	at com.chooloo.www.koler.livedata.ContentProviderLiveData$updateData$1.run(ContentProviderLiveData.kt:37)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

For ex I pasted this [link](https://github.com/shuvashish76)

1. ![Screenshot_2021-09-05-11-49-56](https://user-images.githubusercontent.com/48226312/132117572-8ea15132-deb1-46bf-9927-521fe60772e8.jpeg)

2. ![Screenshot_2021-09-05-11-49-45](https://user-images.githubusercontent.com/48226312/132117575-08dbffaa-e862-4154-bb96-29658fa79d53.jpeg)

**Comment by shuvashish76** [comment]
Thankyou.
not crashing this time.
But after deleting the link. Contacts show empty.
![Screenshot_2021-09-10-01-09-30](https://user-images.githubusercontent.com/48226312/132753514-d2e28e74-6f45-4068-8b72-ab89907d1e3c.jpeg)
But after restarting the app or closing-reopening the app again show all contacts again. Same goes for "Recents"

Checked with **Version v1.1.0 (60)**
