### ISSUE TITLE
Crash while receiving call

### ISSUE THREAD

**Issue by shuvashish76** [Chooloo/koler#265]
FATAL EXCEPTION: main
Process: com.chooloo.www.koler, PID: 879
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1703)
	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1806)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1826)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
	at com.chooloo.www.koler.ui.call.CallActivity.transitionToActiveUI(CallActivity.kt:87)
	at com.chooloo.www.koler.ui.call.CallPresenter.onCallDetailsChanged(CallPresenter.kt:54)
	at com.chooloo.www.koler.ui.call.CallActivity$_callListener$2$1.onCallDetailsChanged(CallActivity.kt:27)
	at com.chooloo.www.koler.util.call.CallManager$CallListener.onStateChanged(CallManager.kt:51)
	at android.telecom.Call$1.run(Call.java:1888)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

- 1.0.9 (F-droid version)
- Android version: 8.1.0
- Device model: Lenovo Tab4 8 Plus (TB-8704X)

**Comment by roeiedri** [comment]
Will release a new version soon, please see if that still happens
